#!/bin/sh

# 提示用户输入必要信息
echo "请输入你的 Cloudflare API token:"
read CF_API_TOKEN

echo "请输入你的 Cloudflare zone ID:"
read CF_ZONE_ID

echo "请输入你的 Cloudflare record ID:"
read CF_RECORD_ID

echo "请输入你想更新的主机名:"
read HOSTNAME

echo "请输入你的 Telegram 机器人 token:"
read TELEGRAM_BOT_TOKEN

echo "请输入你的 Telegram 聊天 ID:"
read TELEGRAM_CHAT_ID

echo "请输入 DDNS 更新的时间间隔（分钟）："
read UPDATE_INTERVAL

# 远程 DDNS 脚本的 URL
REMOTE_SCRIPT_URL="https://raw.githubusercontent.com/liziyu12/alpine-ddns-/main/alpineddns"

# 下载并执行远程 DDNS 脚本
echo "正在下载并执行远程 DDNS 脚本..."
bash <(wget -qO- "$REMOTE_SCRIPT_URL")

# 配置远程脚本所需的信息
echo "正在使用提供的信息配置远程脚本..."

# 设置环境变量以供远程脚本使用
export CF_API_TOKEN
export CF_ZONE_ID
export CF_RECORD_ID
export HOSTNAME
export TELEGRAM_BOT_TOKEN
export TELEGRAM_CHAT_ID

# 设置定时任务，按照指定的时间间隔执行远程 DDNS 脚本
echo "正在设置 Cron 任务以每 $UPDATE_INTERVAL 分钟运行一次远程 DDNS 脚本..."
(crontab -l 2>/dev/null; echo "*/$UPDATE_INTERVAL * * * * bash <(wget -qO- $REMOTE_SCRIPT_URL)") | crontab -

echo "设置完成！"
